### ISSUE TITLE
ROOP extension: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by magickaito** [ashleykleynhans/stable-diffusion-docker#10]
When using this "Stable Diffusion Kohya_ss ComfyUI Ultimate" template on runpod, the roop extension is not working in the Automatic1111 interface.

Uploading a face image , with ROOP "enabled", output has no face swap effect.
It is the same even if I deleted my pod, and restart a brand new pod.

When checking /workspace/logs/webui.log, it appears that the ROOP extension is not installed correctly:

> oot@462be51d70b6:/workspace/logs# cat webui.log
> 
> ################################################################
> Install script for stable-diffusion + Web UI
> Tested on Debian 11 (Bullseye)
> ################################################################
> 
> ################################################################
> Running on root user
> ################################################################
> 
> ################################################################
> Repo already cloned, using it as install directory
> ################################################################
> 
> ################################################################
> python venv already activate or run without venv: /workspace/venv
> ################################################################
> 
> ################################################################
> Launching launch.py...
> ################################################################
> Using TCMalloc: libtcmalloc_minimal.so.4
> Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
> Version: v1.5.1
> Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
> Docker, returning.
> 
> *** Error running install.py for extension /workspace/stable-diffusion-webui/extensions/sd-webui-roop.
> *** Command: "/workspace/venv/bin/python3" "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py"
> *** Error code: 1
> *** stderr: Traceback (most recent call last):
> ***   File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 25, in <module>
> ***     download(model_url, model_path)
> ***   File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/install.py", line 16, in download
> ***     request = urllib.request.urlopen(url)
> ***   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
> ***     return opener.open(url, data, timeout)
> ***   File "/usr/lib/python3.10/urllib/request.py", line 525, in open
> ***     response = meth(req, response)
> ***   File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
> ***     response = self.parent.error(
> ***   File "/usr/lib/python3.10/urllib/request.py", line 563, in error
> ***     return self._call_chain(*args)
> ***   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
> ***     result = func(*args)
> ***   File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
> ***     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> *** urllib.error.HTTPError: HTTP Error 401: Unauthorized
> 
> 
> 
> Launching Web UI with arguments: -f --port 3001 --skip-install --listen --api --xformers --enable-insecure-extension-access --no-half-vae
> 2023-08-23 07:14:09.741307: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-08-23 07:14:12.951525: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> Additional Network extension not installed, Only hijack built-in lora
> LoCon Extension hijack built-in lora successfully
> [-] ADetailer initialized. version: 23.8.0, num models: 9
> 2023-08-23 07:14:40,916 - ControlNet - INFO - ControlNet v1.1.238
> ControlNet preprocessor location: /workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
> 2023-08-23 07:14:41,173 - ControlNet - INFO - ControlNet v1.1.238
> 2023-08-23 07:14:42,708 - roop - INFO - roop v0.0.2
> 2023-08-23 07:14:42,713 - roop - INFO - roop v0.0.2
> Loading weights [1a189f0be6] from /workspace/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors
> Creating model from config: /workspace/stable-diffusion-webui/configs/v1-inference.yaml
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Model loaded in 2.2s (load weights from disk: 0.4s, create model: 0.7s, apply weights to model: 0.5s, apply half(): 0.2s, move model to device: 0.2s).
> Applying attention optimization: xformers... done.
> 2023-08-23 07:14:48,051 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
> 2023-08-23 07:14:48,153 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
> *Deforum ControlNet support: enabled*
> Running on local URL:  http://0.0.0.0:3001
> 
> To create a public link, set `share=True` in `launch()`.
> Startup time: 86.3s (launcher: 40.5s, import torch: 17.0s, import gradio: 1.9s, setup paths: 2.8s, other imports: 2.2s, setup codeformer: 0.3s, load scripts: 19.9s, create ui: 1.1s, gradio launch: 0.3s).
> 100%|██████████| 20/20 [00:01<00:00, 14.11it/s]
> Total progress: 100%|██████████| 20/20 [00:01<00:00, 14.00it/s]
> 100%|██████████| 20/20 [00:01<00:00, 16.33it/s]0:00, 16.26it/s]
> download_path: /root/.insightface/models/buffalo_l0, 16.28it/s]
> Downloading /root/.insightface/models/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
> 100%|██████████| 281857/281857 [00:08<00:00, 35214.29KB/s]
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
> set det-size: (640, 640)
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
> find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
> set det-size: (640, 640)
>                                                                *** Error running postprocess_image: /workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
>     Traceback (most recent call last): [00:16<00:00, 16.28it/s]
>       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 575, in postprocess_image
>         script.postprocess_image(p, pp, *script_args)
>       File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 184, in postprocess_image
>         result: ImageResult = swap_face(
>       File "/workspace/stable-diffusion-webui/extensions/sd-webui-roop/scripts/swapper.py", line 132, in swap_face
>         result = face_swapper.get(result, target_face, source_face)
>     AttributeError: 'NoneType' object has no attribute 'get'
> 
> ---
> 

```

**Comment by ashleykleynhans** [comment]
There is no bug in the template, all of the face swap models ere removed from hugging face, log a bug in the roop extension repo, its not a bug in my template.

**Comment by ashleykleynhans** [comment]
I have forked the roop extension and fixed the issue in my fork.  I have updated my template to include the new fork and tested the roop extension and confirmed that it is working again.  The new template is version 1.8.1.
