### ISSUE TITLE
Error when trying to train Lora as it showed like this in gui.sh

### ISSUE THREAD

**Issue by Rujinopy** [ashleykleynhans/stable-diffusion-docker#11]
This doesn't work for me. I can access the Kohys_ss GUI perfectly in my web browser, but as soon as I click the Train model button:

![image](https://github.com/ashleykleynhans/stable-diffusion-docker/assets/77638197/8b6e7e96-8c4c-49be-aeef-b0e3e40666f2)

**Comment by ashleykleynhans** [comment]
This is just a Docker image, it is not the repo for Kohya_ss, if you have issues with Kohya, then log an issue in the correct repo: https://github.com/bmaltais/kohya_ss

You probably just didn't start Kohya properly, it has to be started with `--headless`.
