### ISSUE TITLE
v1-5-pruned.safetensors: no such file or directory

### ISSUE THREAD

**Issue by JuvenileLocksmith** [ashleykleynhans/stable-diffusion-docker#14]
This one has me beat, tried it all. 

~/stable-diffusion-docker$ ls -l /path/to/v1-5-pruned.safetensors
ls: cannot access '/path/to/v1-5-pruned.safetensors': No such file or directory

**Comment by ashleykleynhans** [comment]
Read the comments in the Dockerfile, it tells you how to download it.

**Comment by JuvenileLocksmith** [comment]
Understood. I am a total newbie and was taken in by the one click docker propaganda. Had found a crude workaround, let me go and see if I have not made things worse.
