### ISSUE TITLE
roop doesn't appear on runpod

### ISSUE THREAD

**Issue by freeexit2002** [ashleykleynhans/stable-diffusion-docker#16]
Stable Diffusion Kohya_ss ComfyUI Ultimate: model of roop doesnt  appear, even i put manually in workspace/stable-diffusion-webui/extensions/sd-webui-roop/inswapper_128.onnx
![Screenshot 2023-09-09 at 19-21-58 Stable Diffusion](https://github.com/ashleykleynhans/stable-diffusion-docker/assets/114404469/71c08bcd-d83d-4eb5-8029-6fd511c8f04f)

**Comment by ashleykleynhans** [comment]
You put the model in the wrong place.

```
mkdir -p /workspace/stable-diffusion-webui/models/roop
cd /workspace/stable-diffusion-webui/models/roop
wget https://huggingface.co/ashleykleynhans/inswapper/resolve/main/inswapper_128.onnx
```

**Comment by freeexit2002** [comment]
Same message: Model not found, please download one and reload automatic 1111. Reload webui and also the pod.
![Screenshot 2023-09-09 at 21-56-47 roop - JupyterLab](https://github.com/ashleykleynhans/stable-diffusion-docker/assets/114404469/bd3bba5f-b44b-447a-93f4-08fae16f3bcd)

**Comment by ashleykleynhans** [comment]
You either put it in the wrong place or did not load the Web UI, its working perfectly for me.
