### ISSUE TITLE
[Feature Request] Lama Cleaner

### ISSUE THREAD

**Issue by DOGMANTC** [ashleykleynhans/stable-diffusion-docker#18]
Either help me make a fork of this with lama cleaner or add it by default, if able.

pretty please

**Comment by ashleykleynhans** [comment]
Don't know what lama cleaner is

**Comment by DOGMANTC** [comment]
> Don't know what lama cleaner is

Then could you just give me a general guide for adding new webui’s to this runpod template?

**Comment by ashleykleynhans** [comment]
> > Don't know what lama cleaner is
> 
> Then could you just give me a general guide for adding new webui’s to this runpod template?

Look at the Dockefile, there are already examples there for Kohya_ss and ComfyUI.

**Comment by DOGMANTC** [comment]
> > > Don't know what lama cleaner is
> > 
> > 
> > Then could you just give me a general guide for adding new webui’s to this runpod template?
> 
> Look at the Dockerfile, there are already examples there for Kohya_ss and ComfyUI.

I’ve been trying since and I haven’t been able to get it working. Could I just request you to put lama cleaner on your todo list?
