### ISSUE TITLE
Latest Tag implementation

### ISSUE THREAD

**Issue by ghzgod** [ashleykleynhans/stable-diffusion-docker#26]
Hello, thank you so much for your docker image.  Could you implement the tag 'latest' so I can stay up to date with my system?  This would allow me to pull the most recent docker image as soon as its available vs checking your docker hub page to see if there is a new image.

Thank you

**Comment by ashleykleynhans** [comment]
`latest` tag added as requested.

**Comment by ghzgod** [comment]
You are awesome!!!  Thank you!
