### ISSUE TITLE
Slow startup time due to unnecessary disk IO

### ISSUE THREAD

**Issue by Shakahs** [ashleykleynhans/stable-diffusion-docker#29]
This container is very slow to start on RunPod, 10-20 minutes even on latest gen secure-cloud pod types with NVMe storage. 
I believe the cause is excess disk IO in pre_start.sh 

https://github.com/ashleykleynhans/stable-diffusion-docker/blob/5f292d1ac8683dfa9f65b04282be2bcd04d90ac7/scripts/pre_start.sh#L13-L14
https://github.com/ashleykleynhans/stable-diffusion-docker/blob/5f292d1ac8683dfa9f65b04282be2bcd04d90ac7/scripts/pre_start.sh#L18-L19
https://github.com/ashleykleynhans/stable-diffusion-docker/blob/5f292d1ac8683dfa9f65b04282be2bcd04d90ac7/scripts/pre_start.sh#L28-L29

These operations are doing a copy + delete of very large directories. This could be significantly optimized by instead _moving_ the existing files to their intended destination directly. 

It's also unclear why rsync is being used, it could be for recursive merging into existing directories but I don't think there are existing directories.
If recursive merging is not needed mv should be used directly. 
If recursive merge is needed, it can be achieved with much better performance by using find and mv like so:
```
cd /path/to/source
find . -type f -exec bash -c 'file="{}"; dir="${file#.}"; target="/path/to/target${dir%/*}"; mkdir -p "$target"; mv "$file" "$target/"' \;
```

**Comment by ashleykleynhans** [comment]
This is to support network volumes and is normal for all RunPod official containers too.
