### ISSUE TITLE
Noob can't start the program

### ISSUE THREAD

**Issue by marshal2107** [ashleykleynhans/stable-diffusion-docker#31]
Sorry for the noob post.

I have successfully built the docker container. With docker desktop app I can run the container, but I don't know how to access to any of the apps.  

I have tried to solve it with chat gpt but could not figure out. 

Any help would be appreciated.

**Comment by ashleykleynhans** [comment]
Connect to the ports according to the port mappings.

<img width="915" alt="Monosnap ashleykleynhans:stable-diffusion-docker: Docker image for Stable Diffusion WebUI with ControlNet, After Detailer, Dreambooth, D… 2023-11-11 17-44-22" src="https://github.com/ashleykleynhans/stable-diffusion-docker/assets/886709/b5094071-66e0-4ba9-a99e-b4242fc50d88">
