### ISSUE TITLE
Regarding the missing repo - runpod-worker-comfyui

### ISSUE THREAD

**Issue by urstrulybala** [ashleykleynhans/stable-diffusion-docker#32]
Hi @ashleykleynhans 
We have been testing our setup with the runpod-worker-comfyUI. But it seems to have been deleted.
Can you let me know how we can proceed? Is the 'stable-diffusion-docker' to be used as the alternate?

Thanks
Bala

**Comment by ashleykleynhans** [comment]
Its not an alternative, its for a pod, not serverless.

i HATE and DETEST comfyui, and people kept wasting my time logging issues, I don't get paid for this work and its it a complete and utter waste of my time supporting shit like ComfyUI so the repo was deleted and I will NEVER EVER support that immense heap of garbage for as long as I live so please stop logging issues about it or you will be blocked.

**Comment by urstrulybala** [comment]
so wow, much calm...thanks anyway.
