### ISSUE TITLE
tail log for kohya_ss on vast.ai

### ISSUE THREAD

**Issue by mihaildomd** [ashleykleynhans/stable-diffusion-docker#33]
hi! great thanks for your images!
i use your kohya_ss image from templates on vast.ai , training works fine, but i cant get full live log

i tried command from readme
`tail -f /workspace/logs/kohya_ss.log`
it doesnt work

tried
`tail -f /kohya_ss/setup.log`
it works only for initial commands, not for training process

can u please help enable training log?

**Comment by ashleykleynhans** [comment]
I don't support Vast.ai, only RunPod unfortunately, this is also for my stable diffusion image, not the Kohya_ss one.
