### ISSUE TITLE
Prompt Travel Extension Install Issue on RUNPOD.

### ISSUE THREAD

**Issue by vlsech** [ashleykleynhans/stable-diffusion-docker#36]
I am running this on RUNPOD.IO with success.  I am having an issue that when I install the PROMPT TRAVEL extension in Stable Diffusion (https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel) it does NOT correctly add MOVIEPY (https://pypi.org/project/moviepy/) as every startup shows:

The log [Prompt-Travel] package moviepy not installed, will not be able to generate video suggesting that the MoviePy package, which is required for video generation in the Prompt Travel extension, is not installed.

Any suggestions on how to fix this?

Thanks,

Vince

**Comment by ashleykleynhans** [comment]
You can try editing:
```
/workspace/stable-diffusion-webui/webui-user.sh
```
And remove `--skip-install` from `COMMANDLINE_ARGS`, and then connect to port 8000 and stop A1111 and start it again.

If that doesn't work, log a Github issue for the extension, because I don't support it.
