### ISSUE TITLE
rsync to /workspace breaks existing venv

### ISSUE THREAD

**Issue by acehoss** [ashleykleynhans/stable-diffusion-docker#41]
I have been using release [3.10.1](https://github.com/ashleykleynhans/stable-diffusion-docker/releases/tag/3.10.1) on RunPod for a week or so and deployed it multiple several after the first provisioning, on A100 and A6000 instances. Each time it starts up fine, and all of my extra A1111 extensions are still installed, all of my models are still downloaded, and my outputs from my last session are still there.

When I deployed the template with the volume today, it took way longer than usual to start up, and I saw it was deploying a new version ([3.11.0](https://github.com/ashleykleynhans/stable-diffusion-docker/releases/tag/3.11.0)). Sadly, after the deployment was complete, A1111 wouldn't start. I looked in the log, and there was a Python error complaining about `pytorch_lightning` missing. So I activated the `venv` and installed it. Then something else was missing, so I installed that. I did that a few more times and came to the conclusion that this wasn't just a thing or two missing after the upgrade. So I ran `pip3 install -r requirements.txt`. I don't remember what the error was after that, but A1111 still wouldn't start.

I `rsync` the workspace regularly to a local drive, so I still have a copy of everything from the last time it worked. After syncing the old `venv` back up to the volume, A1111 started up.

I guess I'm not sure if this template is meant to be run from a volume. I tried it and it worked, so I kept rolling with it. Like I said, it's very handy to use this way, it keeps my customizations in place, and lets me fairly quickly spin up an instance when I need it without transferring in a bunch of models and reinstalling plugins.

Thanks for making this. It works great, except for this little mess. It made it easy for me to get up and running with some beefy GPU resources even as a stable diffusion newbie.

**Comment by leito711** [comment]
Same issue when deploying to local docker container.

**Comment by Zetaphor** [comment]
I assume I'm experiencing the same issue. I didn't SSH into the container, but the Runpod logs stopped at "Copying venv to workspace"

I saw the disk slowly filling but the ports never became available. Ran for 6 minutes without ever becoming available on a 4090 before I finally killed it

**Comment by leito711** [comment]
> I assume I'm experiencing the same issue. I didn't SSH into the container, but the Runpod logs stopped at "Copying venv to workspace"
> 
> I saw the disk slowly filling but the ports never became available. Ran for 6 minutes without ever becoming available on a 4090 before I finally killed it

That does eventually complete, but it's very slow indeed. Could be lack of skill on my side for sure, but I couldnt get any of the versions working in docker, but they are flawless installed directly on my machine (the apps in subject)

**Comment by ashleykleynhans** [comment]
@Zetaphor it takes 20+ minutes to sync on RunPod if you use a Secure Cloud region with network storage, this is not an issue, its normal, use Community cloud if you want it to sync faster.  This is completely unrelated to this issue.

**Comment by ashleykleynhans** [comment]
@leito711 use community cloud, once again this is not a problem and nothing to do with this issue, its a RunPod slow disk issue nothing to do with this project/template.

**Comment by ashleykleynhans** [comment]
Original post and first comment are the only things valid to this issue, please keep this issue focused on the actual problem initially reported.

**Comment by ashleykleynhans** [comment]
I updated the rsync commands but the issue persisted because the `fix_venv.sh` script wasn't fixing the venvs because the `fixed` file was already present.  I have now fixed the bug in the `fix_venv.sh` script and it seems to resolve the issue.

**Comment by ashleykleynhans** [comment]
pip install is still broken

**Comment by ashleykleynhans** [comment]
fix_venv script has been updated and should hopefully now be resolved.
