### ISSUE TITLE
I'm getting an error in Runpod and I don't know what it is. 

### ISSUE THREAD

**Issue by youngeuibae** [ashleykleynhans/stable-diffusion-docker#43]

**Comment by ashleykleynhans** [comment]
What error? Check the logs, this issue is not useful because it doesn't provide any information.

**Comment by youngeuibae** [comment]
Oh. You're the one from Discord. i've resolved the issue and  on my way.  Container is ready and I'm waiting for the app to launch. It's been about 20 minutes and the webui is still not installed. How long will it take to fully install?
<img width="395" alt="image" src="https://github.com/ashleykleynhans/stable-diffusion-docker/assets/127659562/1608d123-669f-4ee4-ab6d-fbef7346f829">

Thank you

**Comment by ashleykleynhans** [comment]
1. Did you use an A5000 in SK region in Community Cloud?
2. Does `nvidia-smi` hang when you run it?

**Comment by youngeuibae** [comment]
Is this what you're asking?


<img width="841" alt="image" src="https://github.com/ashleykleynhans/stable-diffusion-docker/assets/127659562/a18ad213-d93d-4a32-ab58-f9cfc0c62b19">

<img width="541" alt="image" src="https://github.com/ashleykleynhans/stable-diffusion-docker/assets/127659562/820bcaf1-07b7-4bd5-99f6-5261dfff84e8">

**Comment by ashleykleynhans** [comment]
How long did it take nvidia-smi to respond with output?

**Comment by youngeuibae** [comment]
Instantly!
