### ISSUE TITLE
When I try to run the dockerfile, it exits after 1 line of log

### ISSUE THREAD

**Issue by botond1111** [ashleykleynhans/stable-diffusion-docker#47]
Sorry for being nooby, but I'm really new to this environment.

I have installed everything, build the image, pushed it, but when I try to run it in Docker, it doesn't work.
 Here's what the log in Docker says: /usr/bin/env: 'bash\r': No such file or directory
Eagerly waiting for your help!

**Comment by ashleykleynhans** [comment]
You need to built it for the correct platform.  You can Google how to build images for Linux on Mac or Windows.  This is not an issue with the code it works for me and I can't help you with building it, either use my pre-built image or figure it out yourself.
