### ISSUE TITLE
ComfyUI ?

### ISSUE THREAD

**Issue by lounice** [ashleykleynhans/stable-diffusion-docker#5]
Hello Ashleykleynhans,,

I really appreciate your work as your image is up to date and very easy to deploy.
Any chance to add comfyUI to the stack aside webUI and Kohya ?

And a precision if u may ; can you confirm what volumes you recommend when mounting the image ?

Best regards!
lou.

**Comment by ashleykleynhans** [comment]
I'll look at adding ComfyUI since you're not the first person who has requested it.

I recommend adding a persistent storage volume called `/workspace` when mounting the image as pretty much everything is synced there by the container startup scripts.

**Comment by ashleykleynhans** [comment]
ComfyUI has been added.

**Comment by lounice** [comment]
Thank you a lot ashleykleynhans!
One container, 3 UI, it's perfect!!

As for the volume, I did that exactly, but I have errors when the container start, I'll create another issue.

Best regards!
