### ISSUE TITLE
A1111 Forge fork

### ISSUE THREAD

**Issue by mnb3000** [ashleykleynhans/stable-diffusion-docker#53]
Hi! I was wondering if it is possible to adapt this image to use A1111 Forge, so I forked your setup, and on the way made a lot of improvements.

https://github.com/mnb3000/a1111-forge-svd-docker

I decoupled all weights from image, thus making it slimmer and faster to spin up. Weights are now being downloaded at first start of the container and their sha256 checksums are being validated after download.
Image size reduction made it able to set up a CI/CD pipeline which automatically builds, versions, tags, pushes and releases images.
I also added optional SDXL Turbo download as an env var, and SVD 1.1 download from civitai via API token.
If you are interested in backporting these kinds of changes to your repos - let me know, I might be able to help you with that

**Comment by ashleykleynhans** [comment]
https://github.com/ashleykleynhans/forge-docker

**Comment by mnb3000** [comment]
I know you have one, but I needed one with auto SDXL/Turbo/SVD1.1 download, and I did an image for SVD demo code, so I did my twist on it, making a fully working free CI pipeline on the way :)
