### ISSUE TITLE
Rebuild container to update sd-civitai-browser-plus

### ISSUE THREAD

**Issue by LegendaryFling** [ashleykleynhans/stable-diffusion-docker#54]
Could you rebuild the image? BlafKing/sd-civitai-browser-plus#249 needed a hotfix, but since the built container is outdated, it isn't available when the image is deployed.

A workaround is to ssh into the container and run:

```
cd /workspace/stable-diffusion-webui/extensions/sd-civitai-browser-plus;
git pull
```

And then finally restart the container (not the UI).

**Comment by ashleykleynhans** [comment]
The extension has been updated.
