### ISSUE TITLE
Hardware abuse

### ISSUE THREAD

**Issue by itsklimov** [ashleykleynhans/stable-diffusion-docker#59]
As soon as i start the container with an external ip the one of the interfaces starts being used by someone. If i publish the same tools separatly this does not happen.

Is theere a chance the the code reports its location somewhere?

**Comment by ashleykleynhans** [comment]
This is not an issue with this repo.

**Comment by itsklimov** [comment]
I hope so, is there a way to run it in debug mode, to see docker logs in the console?

**Comment by ashleykleynhans** [comment]
Nope, the code is all right here on Github, check it, its not doing anything dodgy.  Also this issue is closed, please stop adding to it and falsely accusing me of doing dodgy things, I don't appreciate the accusations.  You are getting blocked now for being a complete and utter asshole, bye.
