### ISSUE TITLE
Not sure where to start...

### ISSUE THREAD

**Issue by MojoGlover** [ashleykleynhans/stable-diffusion-docker#61]
I'm on runpod, tried to deploy this pod, and I got "bad gateway 502" on port 8000.  I can get to Jupyter... but I don't see the "docker-bake.hcl" file.  Maybe I'm doing something out of order?  Give me a hint, I'm not a programmer, but I want to try comfyui for more control.

**Comment by ashleykleynhans** [comment]
Read container logs, applications are probably syncing to /workspace.  You have to wait for the syncing to complete and for the logs to say that the container is READY before trying to use the pod.
