### ISSUE TITLE
problem with app launcher -- unable to start applications

### ISSUE THREAD

**Issue by rafstahelin** [ashleykleynhans/stable-diffusion-docker#62]
launched Ultimate SD template on a community cloud. Unfortunately the App Launcher is not running. And so cannot start any applications. May need an update

**Comment by ashleykleynhans** [comment]
What app launcher? Check container logs, apps are probably syncing to /workspace if you're talking about the application manager on port 8000.

**Comment by rafstahelin** [comment]
For me rhe container logs were saying that it was ready 
I will try again in a few hours. Thanks man

**Comment by ashleykleynhans** [comment]
Maybe has something to do with CUDA version.  It is now using a CUDA 12.1 base image instead of the previous 11.8 because apparently the newer CUDA versions are more performant, so I suggest using the CUDA filter at the top of the page to select CUDA 12.1, 12.2, 12.3, 12.4 but EXCLUDE 11.8 and 12.0.

**Comment by rafstahelin** [comment]
Ok cool I will try that

**Comment by ashleykleynhans** [comment]
@rafstahelin I have released template version 6.0.4 which reverts the torch and xformers version,  Would you mind trying again please?

**Comment by rafstahelin** [comment]
Yes Give me a few hours At the movies watch Furiosa Thank you Best, Raf On 31 May 2024, at 22:50, Ashley Kleynhans ***@***.***> wrote:﻿
@rafstahelin I have released template version 6.0.4 which reverts the torch and xformers version,  Would you mind trying again please?
