### ISSUE TITLE
Can't connect to any of the features (RunPod)

### ISSUE THREAD

**Issue by popovidis** [ashleykleynhans/stable-diffusion-docker#64]
I am clicking on these and it says that the port is now up yet.

![image](https://github.com/ashleykleynhans/stable-diffusion-docker/assets/120704725/e50257b9-a13f-46c3-80d6-d5040dc8cbba)

**Comment by ashleykleynhans** [comment]
Check container logs, its still syncing to /workspace, you need to wait.

**Comment by popovidis** [comment]
I am sorry didn't realize it would take nearly 1 hour to do so. Is this normal?

2024-06-11T19:34:52Z start container
2024-06-11T20:22:38.114378032Z Container is READY!

**Comment by ashleykleynhans** [comment]
I've improved the syncing process so should be faster now.

**Comment by popovidis** [comment]
Thank you, did you happen to work on others also, like the standalone A1111 image, or Kohya? I believe they all struggle from the same thing.

**Comment by ashleykleynhans** [comment]
All of these have had the improved syncing applied:

* Stable Diffusion Kohya ComfyUI InvokeAI Ultimate
* Text Generation Web UI and APIs
* Stable Diffusion WebUI Forge
* Kohya_ss
* Fooocus
* A1111 Stable Diffusion 1.9.4

**Comment by popovidis** [comment]
Can confirm it was 20 minutes this time for this image
