### ISSUE TITLE
WD14 captioning error

### ISSUE THREAD

**Issue by RicMlg** [ashleykleynhans/stable-diffusion-docker#70]
Hi! In this runpod template: ULTIMATE Stable Diffusion Kohya ComfyUI InvokeAI
WD14 captioning does not work. I think it happens in other captions models. 

Using your template Kohya_ss GUI it works. 

Thanks!

**Comment by ashleykleynhans** [comment]
Which Kohya_ss GUI template are you using?  Mine or AI-Dock one?

**Comment by RicMlg** [comment]
Hi! Yes, yours. This one. thanks!!

ULTIMATE Stable Diffusion Kohya ComfyUI InvokeAI
ashleykza/stable-diffusion-webui:7.0.1






ricardocampos.es
neurona.top

**Comment by ashleykleynhans** [comment]
I was asking which Kohya_ss template you were using where WD14 captioning is working, I was not asking about this template, but I've built version 7.0.2 if you want to try again.

**Comment by RicMlg** [comment]
Ah sorry! Yes, it was yours, this:

Kohya_ss GUI
ashleykza/kohya:24.1.5


Thanks!

ricardocampos.es
neurona.top

**Comment by ashleykleynhans** [comment]
Did you try the 7.0.2 version of the template?

**Comment by RicMlg** [comment]
Now works, thanks!
But the only thing is, in both templates, Prefix to add to WD14 caption  it´s
not working... can you check it if you want. Thanks!

ricardocampos.es
neurona.top

**Comment by RicMlg** [comment]
sorry, my fault. It works perfectly.
Thanks for everything!


ricardocampos.es
neurona.top

**Comment by ashleykleynhans** [comment]
Thanks for pointing it out and helping test.
